### ISSUE TITLE
form表单无法显示

### ISSUE THREAD

**Issue by bjdaijun** [tanjiancheng/gin-amis-admin#3]
amis配置：
`
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "input-text",
        "name": "name",
        "label": "姓名："
      }
    ]
  }
}
`
显示效果：

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1940592/159105630-23c2a7b9-98cd-44fa-97c8-1846f71deb8a.png">

**Comment by tanjiancheng** [comment]
你那个语法是后面aims改过了，2年前不支持的。。。

{
	"type": "page",
	"body": {
		"type": "form",
		"api": "/amis/api/mock2/form/saveForm",
		"controls": [{
			"type": "text",
			"name": "name",
			"label": "姓名："
		}]
	}
}

以上的才可以，目前这个不更新了，有需要可以自己clone然后升级下amis的版本哈

**Comment by cocohao715** [comment]
怎么升级amis的版本
